version: '3.7'

services:

  postgres:
    image: postgres:14.3
    restart: always
    container_name: crudChatBot
    ports:
      - "5632:5432"
    environment:
      POSTGRES_PASSWORD: 8021947cbba
      POSTGRES_DB: crudChatbot
    volumes:
      - ./postgres:/var/lib/postgresql/data
